#include "./linkedList__test.h"

void RUN_ALL_TESTS()
{
  RUN_CREATE_LIST_TESTS();
  RUN_ADDING_NODE_TESTS();
  RUN_SEARCHING_LIST_TESTS();
  RUN_OPERATIONS_LIST_TESTS();
  RUN_DELETING_LIST_TESTS();
}